spring.application.name=Backend-for-Job-Portal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/jobportal

#email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cybersharma073@gmail.com
spring.mail.password=wtnruoblvuypklsc 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

USER_FOUND=user has registered already
USER_NOT_FOUND=User not found in our database
INVALID_CREDENTIALS=Invalid Credentials
OTP_NOT_FOUND=OTP expired
INCORRECT_OTP=OTP is incorrect
JOB_NOT_FOUND=Job not found
JOB_APPLIED_ALREADY=Job applied already


